name: Runs unittests
on: [push]
jobs:
  python:
    runs-on: ubuntu-latest
    container: python:3.10
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v3
      - run: python -m pip install -r requirements.txt
      - run: python -m unittest tests/*.py
  go:
    runs-on: ubuntu-latest
    container: golang:latest
    defaults:
      run:
        working-directory: ./golang
    steps:
      - uses: actions/checkout@v3
      - run: go test
  rust:
    runs-on: ubuntu-latest
    container: rust:latest
    defaults:
      run:
        working-directory: ./rust
    steps:
      - uses: actions/checkout@v3
      - run: cargo test
