name: Runs unittests
on: [push]
jobs:
  python:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - run: python -m pip install -r requirements.txt
      - run: python -m unittest tests/*.py
  go:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./golang
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: ./go.mod
      - run: go test
  rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test